#!/bin/bash
#
# Title:      PSAutomate
# Based On:   PGBlitz (Reference Title File)
# Original Author(s):  Admin9705 - Deiteq
# PSAutomate Auther: fattylewis
# URL:        https://psautomate.io - http://github.psautomate.io
# GNU:        General Public License v3.0
################################################################################
---
- hosts: localhost
  gather_facts: false
  tasks:

    # WP CORE (MANDATORY) #########################################################
    - name: 'Including PG Press Core'
      include_tasks: '/opt/psapress/psapresscore.yml'

    - name: 'Set Known Facts'
      set_fact:
        psarole: '{{wp_id.stdout}}'

    # FACTS #######################################################################
    - name: "Deploy wpdb-{{wp_id.stdout}} Database"
      docker_container:
        name: "wpdb-{{psarole}}"
        image: mariadb
        pull: yes
        expose: 3306
        #published_ports:
        #  - "127.0.0.1:10{{wp_port.stdout}}:3306"
        volumes:
          - "/etc/localtime:/etc/localtime:ro"
          - "/opt/appdata/wordpress/{{wp_id.stdout}}/{{wp_id.stdout}}-db:/var/lib/mysql"
        env:
          MYSQL_ROOT_PASSWORD: "mYsupERbigPas2WorD"
        networks:
          - name: psautomate
            aliases:
              - "wpdb-{{wp_id.stdout}}"
        restart_policy: always
        state: started
